name: TotalFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${project.version}
description: Plugin for the Total Freedom server.
depend: [Aero]
softdepend: [BukkitTelnet, CoreProtect, Essentials, LibsDisguises, Wave, WorldEdit]
authors: [Madgeek1450, Prozza]
api-version: 1.13
