name: TotalFreedomMod
version: ${project.version}
description: Plugin for the Total Freedom server.
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
depend: [Aero]
softdepend: [BukkitTelnet, CoreProtect, Essentials, LibsDisguises, WorldEdit]
authors: [Madgeek1450, Prozza]
api-version: 1.14
